services:
  - type: web
    name: super30-text-api
    env: python
    buildCommand: pip install -r requirement.txt
    startCommand: python app.py
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 10000